version: "3.8"

networks:
  hyggdrasil:
    driver: overlay

services:
  redis:
    image: redis:7.0.4
    networks:
      - hyggdrasil
    command: redis-server --requirepass JNF25u8JwzR67u9GNpQn9v7wm28rPQ --save 60 1
    volumes:
      - ./redis:/data

  hyggdrasil:
    image: hyggdrasil:latest
    networks:
      - hyggdrasil
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/:/usr/app/data
      - ./images:/usr/app/images
