version: "3.8"

networks:
  hyriode:
    driver: overlay

services:
  redis:
    image: redis:6.2.6-alpine
    networks:
      - hyriode
    command: redis-server --requirepass p@ssw0rd

  hyggdrasil:
    image: hyggdrasil:latest
    networks:
      - hyriode
    environment:
      STACK_NAME: hyggdrasil
      NETWORK_NAME: hyriode
      REDIS_HOST: redis
      REDIS_PASS: p@ssw0rd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/:/usr/app/data