FROM itzg/bungeecord:latest

# Override default envs
ENV TYPE="CUSTOM" BUNGEE_JAR_URL="https://hyriode.fr/bungeecord.jar" ENABLE_RCON="FALSE" HEALTH_USE_PROXY="TRUE" MAX_MEMORY="2G" INIT_MEMORY="256M"

# Disable healthcheck
HEALTHCHECK NONE
