name: Docker Dev Workflow

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and tag image
        run: docker build -t "ghcr.io/hyriode/hyggdrasil:dev" -f Dockerfile . --build-arg GITHUB_USERNAME=$GITHUB_ACTOR --build-arg GITHUB_TOKEN=$GITHUB_TOKEN
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Docker login
        run: docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        shell: bash

      - name: Publish to GPR
        run: docker push "ghcr.io/hyriode/hyggdrasil:dev"
        shell: bash