name: Publish CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Publish to GitHub Packages
        run: |
          cd API
          gradle publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.TOKEN }}